//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Bodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class canasta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public canasta()
        {
            this.canasta_detalle = new HashSet<canasta_detalle>();
        }
    
        public int rowid { get; set; }
        public int rowid_bodega { get; set; }
        public int pasillo { get; set; }
        public string bloque { get; set; }
        public int canasta1 { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canasta_detalle> canasta_detalle { get; set; }
    }
}
