//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Bodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class computador
    {
        public int rowid { get; set; }
        public int rowid_producto { get; set; }
        public int rowid_procesador { get; set; }
        public string nombre { get; set; }
        public string mac { get; set; }
        public string mac_wifi { get; set; }
        public string ip { get; set; }
        public string ip_wifi { get; set; }
        public int memoria { get; set; }
        public int disco1 { get; set; }
        public Nullable<int> disco2 { get; set; }
        public Nullable<int> disco3 { get; set; }
        public int rowid_sistema { get; set; }
        public Nullable<int> bits { get; set; }
    
        public virtual procesador procesador { get; set; }
        public virtual producto producto { get; set; }
        public virtual sistema sistema { get; set; }
    }
}
