//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Bodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historico
    {
        public int rowid { get; set; }
        public int rowid_producto { get; set; }
        public System.DateTime fecha { get; set; }
        public string conexion { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
