//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Bodega.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tecnologiaEntities : DbContext
    {
        public tecnologiaEntities()
            : base("name=tecnologiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Bodegas> Bodegas { get; set; }
        public virtual DbSet<SKU> SKU { get; set; }
        public virtual DbSet<asignacion> asignacion { get; set; }
        public virtual DbSet<computador> computador { get; set; }
        public virtual DbSet<historico> historico { get; set; }
        public virtual DbSet<impresora> impresora { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<procesador> procesador { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<sistema> sistema { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<canasta> canasta { get; set; }
        public virtual DbSet<canasta_detalle> canasta_detalle { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Canastas> Canastas { get; set; }
    }
}
