//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Bodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU
    {
        public int rowid { get; set; }
        public string barras { get; set; }
        public string referencia { get; set; }
        public string talla { get; set; }
        public string color { get; set; }
        public short estado { get; set; }
    }
}
