//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Bodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int RowID { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
        public Nullable<int> Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> RolID { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string Img_DocIdentidad { get; set; }
        public string Bodega { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<bool> ind_cambiarClave { get; set; }
    }
}
